version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: mongoose
    versions:
    - "> 5.9.20"
  - dependency-name: markdown-table
    versions:
    - 3.0.0
